#!/bin/bash

gpl=diffusion.gpl

gnuplot $gpl 
#sed -i 's/tof/tofexpansion\/tof/g' tof.tex
#sed -i 's/put(0,0)/put(500,0)/g' tof.tex

latex diffusioneps.tex; dvips diffusioneps.dvi -o diffusioneps.eps

ps2eps -f diffusioneps.eps
mv diffusioneps.eps.eps diffusioneps.eps
epstopdf diffusioneps.eps


