#!/bin/bash

gpl=photoionization.gpl

gnuplot $gpl 
#sed -i 's/tof/tofexpansion\/tof/g' tof.tex
#sed -i 's/put(0,0)/put(500,0)/g' tof.tex

latex phioneps.tex; dvips phioneps.dvi -o phioneps.eps

ps2eps -f phioneps.eps
mv phioneps.eps.eps phioneps.eps
 
epstopdf phioneps.eps

