#!/bin/bash

gpl=evap.gpl

gnuplot $gpl 
#sed -i 's/evap/evaporation\/evap/g' evap.tex
sed -i 's/put(0,0)/put(0,0)/g' evap.tex
#sed -i 's/put(0,0)/put(525,0)/g' evap_standalone.tex

latex evapeps.tex; dvips evapeps.dvi -o evapeps.eps

ps2eps -f evapeps.eps
mv evapeps.eps.eps evapeps.eps

epstopdf evapeps.eps
