#!/bin/bash

gpl=uvdet.gpl

gnuplot $gpl 
#sed -i 's/tof/tofexpansion\/tof/g' tof.tex
#sed -i 's/put(0,0)/put(500,0)/g' tof.tex

latex uvdeteps.tex; dvips uvdeteps.dvi -o uvdeteps.eps

ps2eps -f uvdeteps.eps
mv uvdeteps.eps.eps uvdeteps.eps
epstopdf uvdeteps.eps
