#!/bin/bash

gpl=lockfig.gpl

gnuplot $gpl 
#sed -i 's/evap/evaporation\/evap/g' evap.tex
#sed -i 's/put(0,0)/put(525,0)/g' evap.tex
#sed -i 's/put(0,0)/put(525,0)/g' evap_standalone.tex

latex lockfigeps.tex; dvips lockfigeps.dvi -o lockfigeps.eps

ps2eps -f lockfigeps.eps
mv lockfigeps.eps.eps lockfigeps.eps
epstopdf lockfigeps.eps
