#!/bin/bash

gpl=errsig.gpl

gnuplot $gpl 
#sed -i 's/evap/evaporation\/evap/g' evap.tex
#sed -i 's/put(0,0)/put(525,0)/g' evap.tex
#sed -i 's/put(0,0)/put(525,0)/g' evap_standalone.tex

latex errsigeps.tex; dvips errsigeps.dvi -o errsigeps.eps

ps2eps -f errsigeps.eps
mv errsigeps.eps.eps errsigeps.eps
epstopdf errsigeps.eps
