#!/bin/bash

gpl=lightshift.gpl

gnuplot $gpl 
#sed -i 's/lightshift/lightshift\/lightshift/g' lightshift.tex
#sed -i 's/put(0,0)/put(500,0)/g' evap.tex
latex lightshifteps.tex; dvips lightshifteps.dvi -o lightshifteps.eps

ps2eps -f lightshifteps.eps
mv lightshifteps.eps.eps lightshifteps.eps

epstopdf lightshifteps.eps
