#!/bin/bash


rRED=7334_7340.TOFDAT
NRED=7334_7340.NUMDAT
RED=7334_7340.TOF

rUV=110719_7505to7522.TOFDAT
NUV=110719_7505to7522.NUMDAT
UV=110719_7505to7522.TOF

rCNC=110720_7568to7573,7593to7604.TOFDAT
NCNC=110720_7568to7573,7593to7604.NUMDAT
CNC=110720_7568to7573,7593to7604.TOF

TRED=`awk 'NR==2 { printf("%.3f",$1)}' $RED`
TRED_err=`awk 'NR==2 { printf("%.3f",$2)}' $RED`

r0RED=`awk 'NR==2 { printf("%.3f",$3)}' $RED`
r0RED_err=`awk 'NR==2 { printf("%.3f",$4)}' $RED`

N0RED=`awk 'NR==2 { printf("%.3e",$11)}' $RED`
N0RED_err=`awk 'NR==2 { printf("%.3e",$12)}' $RED`

nRED=`awk 'NR==2 { printf("%.3e",$13)}' $RED`
nRED_err=`awk 'NR==2 { printf("%.3e",$14)}' $RED`

pRED=`awk 'NR==2 { printf("%.1e",$15)}' $RED`
pRED_err=`awk 'NR==2 { printf("%.1e",$16)}' $RED`

echo "-------- REDMOT --------"
echo " T = $TRED  +/- $TRED_err" 
echo "r0 = $r0RED +/- $r0RED_err" 
echo " N = $N0RED +/- $N0RED_err"
echo " n = $nRED  +/- $nRED_err"
echo " p = $pRED  +/- $pRED_err" 

TUV=`awk 'NR==2 { printf("%.3f",$1)}' $UV`
TUV_err=`awk 'NR==2 { printf("%.3f",$2)}' $UV`

r0UV=`awk 'NR==2 { printf("%.3f",$3)}' $UV`
r0UV_err=`awk 'NR==2 { printf("%.3f",$4)}' $UV`

N0UV=`awk 'NR==2 { printf("%.3e",$5)}' $UV`
N0UV_err=`awk 'NR==2 { printf("%.3e",$6)}' $UV`

nUV=`awk 'NR==2 { printf("%.3e",$7)}' $UV`
nUV_err=`awk 'NR==2 { printf("%.3e",$8)}' $UV`

pUV=`awk 'NR==2 { printf("%.1e",$9)}' $UV`
pUV_err=`awk 'NR==2 { printf("%.1e",$10)}' $UV`

echo "-------- UVMOT --------"
echo " T = $TUV  +/- $TUV_err" 
echo "r0 = $r0UV +/- $r0UV_err" 
echo " N = $N0UV +/- $N0UV_err"
echo " n = $nUV  +/- $nUV_err"
echo " p = $pUV  +/- $pUV_err" 

TCNC=`awk 'NR==2 { printf("%.3f",$1)}' $CNC`
TCNC_err=`awk 'NR==2 { printf("%.3f",$2)}' $CNC`

r0CNC=`awk 'NR==2 { printf("%.3f",$3)}' $CNC`
r0CNC_err=`awk 'NR==2 { printf("%.3f",$4)}' $CNC`

N0CNC=`awk 'NR==2 { printf("%.3e",$5)}' $CNC`
N0CNC_err=`awk 'NR==2 { printf("%.3e",$6)}' $CNC`

nCNC=`awk 'NR==2 { printf("%.3e",$7)}' $CNC`
nCNC_err=`awk 'NR==2 { printf("%.3e",$8)}' $CNC`

pCNC=`awk 'NR==2 { printf("%.1e",$9)}' $CNC`
pCNC_err=`awk 'NR==2 { printf("%.1e",$10)}' $CNC`

echo "-------- CNCMOT --------"
echo " T = $TCNC  +/- $TCNC_err" 
echo "r0 = $r0CNC +/- $r0CNC_err" 
echo " N = $N0CNC +/- $N0CNC_err"
echo " n = $nCNC  +/- $nCNC_err"
echo " p = $pCNC  +/- $pCNC_err" 



gpl=tof.gpl
rm -f $gpl

echo "reset " >> $gpl
echo "set fit errorvariables" >> $gpl
echo "set fit logfile \"mylog.fit\"" >> $gpl
echo "kbm=13.85e-06 #kb/m in cm^2/ms^2/uK" >> $gpl

echo "rUV(x)= x>0?sqrt($r0UV**2+2*kbm*$TUV*x**2):$r0UV" >>$gpl
echo "rCNC(x)= x>0?sqrt($r0CNC**2+2*kbm*$TCNC*x**2):$r0CNC" >>$gpl
echo "rRED(x)= x>0?sqrt($r0RED**2+2*kbm*$TRED*x**2):$r0RED" >>$gpl

echo "set xl \"\\\\sf  Time of flight \(ms\)\" offset 0,0.5;" >> $gpl
echo 'set yl "\\sf  $\\mathsf{e}^{\\mathsf{-1}}$ cloud radius (cm)" offset 4.5,0;' >> $gpl
echo "set xr [0:5]" >> $gpl

echo "set ytics (\"\\\\sf 0.1\" 0.1, \"\\\\sf 0.1\" 0.2, \"\\\\sf 0.3\" 0.3, \"\\\\sf 0.4\" 0.4, \"\\\\sf 0.5\" 0.5)" >> $gpl
echo "set mytics 4" >> $gpl

echo "set xtics (\"\\\\sf 0\" 0, \"\\\\sf 1\" 1, \"\\\\sf 2\" 2, \"\\\\sf 3\" 3, \"\\\\sf 4\" 4, \"\\\\sf 5\" 5)" >> $gpl
echo "set mxtics 2" >> $gpl

echo "TUV=$TUV" >> $gpl
echo "TUV_err=$TUV" >> $gpl
echo "pUV=$pUV" >> $gpl
echo "pUV_err=$pUV_err" >> $gpl

echo "TCNC=$TCNC" >> $gpl
echo "TCNC_err=$TCNC" >> $gpl
echo "pCNC=$pCNC" >> $gpl
echo "pCNC_err=$pCNC_err" >> $gpl

echo "TRED=$TRED" >> $gpl
echo "TRED_err=$TRED" >> $gpl
echo "pRED=$pRED" >> $gpl
echo "pRED_err=$pRED_err" >> $gpl

echo "ls=0.027" >> $gpl

echo "set terminal epslatex size 3.85,2.8 color lw 3" >> $gpl
echo "set size 1,0.9" >> $gpl

echo "set output \"tofstandalone-SS.tex\" " >> $gpl


printf 'set label 1 \"$T = %.0f\\\\pm %.0f \\\\ \\\\mu$K\" at 2.6,0.255\n' $TCNC $TCNC_err >> $gpl 
printf 'set label 2 \"$\\\\rho_{\\\\mathrm{ps}} = %.1f\\\\times10^{-6}$\" at 2.6,0.255-ls\n' `echo "" | awk -v a=$pCNC '{print a*1e6}'` >> $gpl
printf 'set label 3 \"$T = %.0f\\\\pm %.0f \\\\ \\\\mu$K\" at 0.2,0.46\n' $TRED $TRED_err >> $gpl
printf 'set label 4 \"$\\\\rho_{\\\\mathrm{ps}} = %.1f\\\\times10^{-7}$\" at 0.2,0.46-ls\n' `echo "" | awk -v a=$pRED '{print a*1e7}'` >> $gpl

echo "set key 4.35, 0.48 samplen 0.5;" >> $gpl
echo "set yr [0.15:0.5]" >> $gpl

echo "plot \\" >> $gpl
echo "\"$rRED\" u 1:4 lc rgbcolor \"#000000\" ps 2.0 pt 9 title \"\\\\sf MOT\" ,\\" >> $gpl
echo "\"$rCNC\" u 1:2 lc rgbcolor \"red\" ps 2.0 pt 5 title \"\\\\sf CMOT\" ,\\" >> $gpl
echo "rCNC(x) lw 2 lc rgbcolor \"red\" notitle,\\" >> $gpl
echo "rRED(x) lw 2 lc rgbcolor \"#000000\" notitle" >>$gpl

echo "unset label 1" >> $gpl
echo "unset label 2" >> $gpl
echo "unset label 3" >> $gpl
echo "unset label 4" >> $gpl

echo "set key 4.8, 0.13 samplen 0.5;" >> $gpl
echo "set yr [0.05:0.4]" >> $gpl

echo "set output \"tofstandalone.tex\" " >> $gpl

printf 'set label 1 \"$T = %.0f\\\\pm %.0f \\\\ \\\\mu$K\" at 0.6,0.35\n' $TCNC $TCNC_err >> $gpl 
printf 'set label 2 \"$\\\\rho_{\\\\mathrm{ps}} = %.1f\\\\times10^{-6}$\" at 0.6,0.35-ls\n' `echo "" | awk -v a=$pCNC '{print a*1e6}'` >> $gpl
printf 'set label 3 \"$T = %.0f\\\\pm %.0f \\\\ \\\\mu$K\" at 2.7,0.265\n' $TUV $TUV_err >> $gpl
printf 'set label 4 \"$\\\\rho_{\\\\mathrm{ps}} = %.1f\\\\times10^{-5}$\" at 2.7,0.265-ls\n' `echo "" | awk -v a=$pUV '{print a*1e5}'` >> $gpl



echo "plot \\" >> $gpl
echo "\"$rCNC\" u 1:2 lc rgbcolor \"red\" ps 2.0 pt 5 title \"\\\\sf CMOT (671 nm)\" ,\\" >> $gpl
echo "\"$rUV\" u 1:2 lc rgbcolor \"#7030A0\" ps 2.0 pt 7 title \"\\\\sf UVMOT (323 nm)\" ,\\" >> $gpl
echo "rCNC(x) lw 2 lc rgbcolor \"red\" notitle,\\" >> $gpl
echo "rUV(x) lw 2 lc rgbcolor \"#7030A0\" notitle" >>$gpl

printf 'set label 5 \"{\\\\Large \\\\bf (a)}\" at -0.8,0.40-ls\n' >> $gpl
echo "set output \"tof.tex\" " >> $gpl
echo "replot " >> $gpl

gnuplot $gpl 
sed -i 's/tof/tofexpansion\/tof/g' tof.tex
#sed -i 's/put(0,0)/put(500,0)/g' tof.tex

latex tofeps.tex; dvips tofeps.dvi -o tofeps.eps
latex tofeps-SS.tex; dvips tofeps-SS.dvi -o tofeps-SS.eps


ps2eps -f tofeps.eps
mv tofeps.eps.eps tofeps.eps
epstopdf tofeps.eps

ps2eps -f tofeps-SS.eps
mv tofeps-SS.eps.eps tofeps-SS.eps
epstopdf tofeps-SS.eps

