#!/bin/bash

gpl=feshbach.gpl

gnuplot $gpl 
#sed -i 's/tof/tofexpansion\/tof/g' tof.tex
#sed -i 's/put(0,0)/put(500,0)/g' tof.tex

latex feshbacheps.tex; dvips feshbacheps.dvi -o feshbacheps.eps

ps2eps -f feshbacheps.eps
mv feshbacheps.eps.eps feshbacheps.eps
epstopdf feshbacheps.eps

