#!/bin/bash

gpl=uvreppow.gpl

gnuplot $gpl 
#sed -i 's/tof/tofexpansion\/tof/g' tof.tex
#sed -i 's/put(0,0)/put(500,0)/g' tof.tex

latex uvreppoweps.tex; dvips uvreppoweps.dvi -o uvreppoweps.eps

ps2eps -f uvreppoweps.eps
mv uvreppoweps.eps.eps uvreppoweps.eps
epstopdf uvreppoweps.eps
